title: Tom Stammers
author: Tom Stammers
description: Just another jekyll website
url: https://tomstammers.co.uk
timezone: Europe/London

links:
  github: https://github.com/t-stammers
  linkedin: https://www.linkedin.com/in/thomasstammers
  instagram: https://www.instagram.com/tom.stammers_producing
  jekyll: https://jekyllrb.com

collections:
  posts:
    output: true
    permalink: /articles/:title

paginate: 8
paginate_path: /articles/:num

sass:
  style: compressed
strict_front_matter: true

twitter:
  username: pixyzehn
  card: summary

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
- jekyll-redirect-from

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
