# Setup
title:               Tom Stammers
tagline:             'Sound'
description:         'This is a test of a website'
url:                 http://t-stammers.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tom Stammers
  url:               https://tomstammers.co.uk
  email:             tomstammers16@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-XXXX-Y
